### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by Kamba56** [caasperr/To-Do-List-#4] opened 2022-06-03 07:28 UTC
The repo is well documented.
All the functionalities function as they are suppose to.

You can try splitting your js code into modules and import them rather than having alot of code in a single js file.

**Comment by developerwaleed** [comment] 2022-06-06 16:11
Hey, Toma Thank you for you your kind feedback I want to tell you that I did refactor my code and did divide it into modules :) and as the issue is now solved so I would like to close it Thank you! 😊

**Closed as completed by developerwaleed** 2022-06-06 16:11 UTC
